# Generated by Django 4.2.1 on 2023-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
