# Generated by Django 4.2.1 on 2023-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_superadmin_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_one',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_two',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
