# Generated by Django 4.2.1 on 2023-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
