# Generated by Django 4.2.1 on 2023-07-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bus_tax_cert',
            field=models.ImageField(default=False, upload_to='business/taxCert'),
            preserve_default=False,
        ),
    ]
