# Generated by Django 4.2.1 on 2023-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_bus_tax_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bus_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
