# Generated by Django 4.2.1 on 2023-08-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_openhours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openhours',
            old_name='is_cloased',
            new_name='is_closed',
        ),
    ]
