# Generated by Django 4.2.1 on 2023-08-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_rename_is_cloased_openhours_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openhours',
            options={'ordering': ('day', '-from_hour')},
        ),
        migrations.AlterUniqueTogether(
            name='openhours',
            unique_together={('business', 'day', 'from_hour', 'to_hour')},
        ),
    ]
