# Generated by Django 4.2.1 on 2023-08-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_openhours_options_and_more'),
        ('orders', '0003_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='businesses',
            field=models.ManyToManyField(blank=True, to='business.business'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
