# Generated by Django 4.2.1 on 2023-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_businesses_order_total_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format: {'service_type':{'service_percentage':'tax_amount'}}", null=True),
        ),
    ]
